In [1]:
include("../GameAnalysis.jl")
using SymmetricTensors
using Plots
using LaTeXStrings
using DataFrames, CSV

In [3]:
st_sizes = zeros(Int64, 13, 3)
st_size_df = DataFrame(players=Int[], actions=Int[], size=Int[])
for num_actions in 4:6
    for num_players in 2:14
        if(num_actions == 4 || num_players < 13)
            s = num_actions * Base.summarysize(SymmetricTensor(ones([num_actions for i in 1:num_players]...), 2))
            st_sizes[num_players-1, num_actions-3] = s
            push!(st_size_df, (num_players, num_actions, s))
        end
    end
end
CSV.write("../data/sym_tens_sizes.csv", st_size_df)
st_sizes

13×3 Matrix{Int64}:
    1312      2640      3504
    2400      5880      8544
    4576     13080     21024
    9120     29800     52608
   18848     70560    133776
   39904    174200    344160
   85600    446760    892416
  184608   1183080   2328960
  398368   3216240   6120432
  857952   8932600  16224096
 1841888  25245240  43466976
 3940000         0         0
 8397472         0         0

In [2]:
st_size_df = DataFrame(CSV.File("../data/sym_tens_sizes.csv"))

39×3 DataFrame
 Row │ players  actions  size     
     │ Int64    Int64    Int64    
─────┼────────────────────────────
   1 │       2        4      1312
   2 │       3        4      2400
   3 │       4        4      4576
   4 │       5        4      9120
   5 │       6        4     18848
   6 │       7        4     39904
   7 │       8        4     85600
   8 │       9        4    184608
  ⋮  │    ⋮        ⋮        ⋮
  33 │       8        6    892416
  34 │       9        6   2328960
  35 │      10        6   6120432
  36 │      11        6  16224096
  37 │      12        6  43466976
  38 │      13        6         0
  39 │      14        6         0
                   24 rows omitted

In [24]:
sg_sizes = zeros(Int64, 15, 3)
sg_size_df = DataFrame(players=Int[], actions=Int[], size=Int[])
for num_actions in 4:6
    for num_players in 2:16
        s = Base.summarysize(RepeatsTable(num_players,num_actions,c->ones(size(c))))
        sg_sizes[num_players-1, num_actions-3] = s
        push!(sg_size_df, (num_players, num_actions, s))
    end
end
CSV.write("../data/rep_table_sizes.csv", sg_size_df)
sg_sizes

15×3 Matrix{Int64}:
  1136    1976     3200
  2096    4376     8240
  3536    8576    18320
  5552   15296    36464
  8240   25376    66704
 11696   39776   114224
 16016   59576   185504
 21296   85976   288464
 27632  120296   432608
 35120  163976   629168
 43856  218576   891248
 53936  285776  1233968
 65456  367376  1674608
 78512  465296  2232752
 93200  581576  2930432

In [3]:
sg_size_df = DataFrame(CSV.File("../data/rep_table_sizes.csv"))

45×3 DataFrame
 Row │ players  actions  size    
     │ Int64    Int64    Int64   
─────┼───────────────────────────
   1 │       2        4     1136
   2 │       3        4     2096
   3 │       4        4     3536
   4 │       5        4     5552
   5 │       6        4     8240
   6 │       7        4    11696
   7 │       8        4    16016
   8 │       9        4    21296
  ⋮  │    ⋮        ⋮        ⋮
  39 │      10        6   432608
  40 │      11        6   629168
  41 │      12        6   891248
  42 │      13        6  1233968
  43 │      14        6  1674608
  44 │      15        6  2232752
  45 │      16        6  2930432
                  30 rows omitted

In [29]:
asym_size_df = DataFrame(players=Int[], actions=Int[], size=Int[])
for num_actions in 4:6
    for num_players in 2:16
        push!(asym_size_df, (num_players, num_actions, num_players*num_actions^num_players+40))
    end
end
CSV.write("../data/asym_nfg_sizes.csv", sg_size_df)
asym_sizes = [p*s^p+40 for p=2:12, s=4:6] # n-element Julia float arrays appear to take take 8*n + 40 bytes


11×3 Matrix{Int64}:
        72          90          112
       232         415          688
      1064        2540         5224
      5160       15665        38920
     24616       93790       279976
    114728      546915      1959592
    524328     3125040     13436968
   2359336    17578165     90699304
  10485800    97656290    604661800
  46137384   537109415   3990767656
 201326632  2929687540  26121388072

In [30]:
asym_size_df = DataFrame(CSV.File("../data/asym_nfg_sizes.csv"))

45×3 DataFrame
 Row │ players  actions  size    
     │ Int64    Int64    Int64   
─────┼───────────────────────────
   1 │       2        4     1136
   2 │       3        4     2096
   3 │       4        4     3536
   4 │       5        4     5552
   5 │       6        4     8240
   6 │       7        4    11696
   7 │       8        4    16016
   8 │       9        4    21296
  ⋮  │    ⋮        ⋮        ⋮
  39 │      10        6   432608
  40 │      11        6   629168
  41 │      12        6   891248
  42 │      13        6  1233968
  43 │      14        6  1674608
  44 │      15        6  2232752
  45 │      16        6  2930432
                  30 rows omitted

In [36]:
plot(legend=(0.1,0.95), xlabel=L"Number of Players, $P$", ylabel="Bytes of Memory", legend_font_pointsize=8)
plot!(2:10,asym_sizes[1:9,1], label="Normal Form, A=4", lw = 3, ls=:dot, seriescolor=1, thickness_scaling = 1, markershape=:diamond)
plot!(2:9,asym_sizes[1:8,2], label="Normal Form, A=5", lw = 3, ls=:dot, seriescolor=2, markershape=:diamond)
plot!(2:8,asym_sizes[1:7,3], label="Normal Form, A=6", lw = 3, ls=:dot, seriescolor=3, markershape=:diamond)
plot!(2:14,st_size_df[st_size_df.actions .== 4,:].size[1:13], label="Sym. Tensors, A=4", lw = 3, ls=:dash, seriescolor=1, markershape=:utriangle)
plot!(2:11,st_size_df[st_size_df.actions .== 5,:].size[1:10], label="Sym. Tensors, A=5", lw = 3, ls=:dash, seriescolor=2, markershape=:utriangle)
plot!(2:11,st_size_df[st_size_df.actions .== 6,:].size[1:10], label="Sym. Tensors, A=6", lw = 3, ls=:dash, seriescolor=3, markershape=:utriangle)
plot!(2:16,sg_size_df[sg_size_df.actions .== 4,:].size[1:15], label="Pre-Comp. Reps. A=4", lw = 3, seriescolor=1, markershape=:circle)
plot!(2:16,sg_size_df[sg_size_df.actions .== 5,:].size[1:15], label="Pre-Comp. Reps. A=5", lw = 3, seriescolor=2, markershape=:circle)
plot!(2:16,sg_size_df[sg_size_df.actions .== 6,:].size[1:15], label="Pre-Comp. Reps. A=6", lw = 3, seriescolor=3, markershape=:circle)
xticks!(2:2:16)
ylims!((0,0.8e7))
yt = 0:2e6:0.8e7
yt_labels = ["0","2M","4M","6M","8M"]
plot!(yticks=(yt, yt_labels))
# savefig("../figures/NFG_memory_comparison.png")


In [31]:
st_size_df[st_size_df.actions .== 4,:]

13×3 DataFrame
 Row │ players  actions  size    
     │ Int64    Int64    Int64   
─────┼───────────────────────────
   1 │       2        4     1312
   2 │       3        4     2400
   3 │       4        4     4576
   4 │       5        4     9120
   5 │       6        4    18848
   6 │       7        4    39904
   7 │       8        4    85600
   8 │       9        4   184608
   9 │      10        4   398368
  10 │      11        4   857952
  11 │      12        4  1841888
  12 │      13        4  3940000
  13 │      14        4  8397472

In [28]:
asym_size_df[asym_size_df.actions .== 4,:]

15×3 DataFrame
 Row │ players  actions  size  
     │ Int64    Int64    Int64 
─────┼─────────────────────────
   1 │       2        4   1136
   2 │       3        4   2096
   3 │       4        4   3536
   4 │       5        4   5552
   5 │       6        4   8240
   6 │       7        4  11696
   7 │       8        4  16016
   8 │       9        4  21296
   9 │      10        4  27632
  10 │      11        4  35120
  11 │      12        4  43856
  12 │      13        4  53936
  13 │      14        4  65456
  14 │      15        4  78512
  15 │      16        4  93200