In [1]:
M = Array(reshape(1:4*5, 4,5))
k = zeros(Bool, 4)
k[2:3] .= 1
display(M[k,:])
l = zeros(Bool, 5)
l[2:3] .= 1
display(M[:,l])

2×5 Matrix{Int64}:
 2  6  10  14  18
 3  7  11  15  19

4×2 Matrix{Int64}:
 5   9
 6  10
 7  11
 8  12

In [41]:
T = Array(reshape(1:2*3*4, 2,3,4))
i = zeros(Bool, 2,3)
i[1,2:3] .= 1
display(T[i,:])
j = zeros(Bool, 3,4)
j[1:2,3:4] .= 1
display(T[:,j])

2×4 Matrix{Int64}:
 3   9  15  21
 5  11  17  23

LoadError: BoundsError: attempt to access 2×3×4 Array{Int64, 3} at index [1:2, 3×4 Matrix{Bool}]

In [39]:
T

2×3×4 Array{Int64, 3}:
[:, :, 1] =
 1  3  5
 2  4  6

[:, :, 2] =
 7   9  11
 8  10  12

[:, :, 3] =
 13  15  17
 14  16  18

[:, :, 4] =
 19  21  23
 20  22  24

In [40]:
for i = 1:2
    display(T[i,:,:])
end
# T[:,findall(j)] .= 0
# for i = 1:2
#     display(T[i,:,:])
# end

3×4 Matrix{Int64}:
 1   7  13  19
 3   9  15  21
 5  11  17  23

3×4 Matrix{Int64}:
 2   8  14  20
 4  10  16  22
 6  12  18  24

In [42]:
display(j)
display(findall(j))

3×4 Matrix{Bool}:
 0  0  1  1
 0  0  1  1
 0  0  0  0

4-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 CartesianIndex(1, 4)
 CartesianIndex(2, 4)

In [43]:
T[:,findall(j)]

2×4 Matrix{Int64}:
 13  15  19  21
 14  16  20  22